events {}
http {
  server {
    listen 80;
  location = /health {
    access_log off;
    default_type application/json;
    return 200 '{"status":"ok"}';
  }
    location /api/auth/ {
    proxy_pass http://auth-service:8000/auth/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/documents/ {
    proxy_pass http://document-service:8001/documents/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/ingestion/ {
    proxy_pass http://ingestion-service:8002/ingestion/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /api/chat/ {
    proxy_pass http://chat-service:8003/chat/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
  }
}
